name: MattsPullRequestHelper
description: A GitHub Action to analyze changed files and test methods in pull requests.
author: Matt Lacey
inputs:
  github-token:
    description: The GitHub token to authenticate API requests.
    required: true
  workspace:
    description: The GitHub workspace directory.
    required: false
    default: ${{ github.workspace }}

runs:
  using: composite
  steps:
    - name: Set up .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '9.0'

    - name: Restore dependencies
      run: dotnet restore MyGithubActionBot/MyGithubActionBot.csproj
      shell: bash

    - name: Build the project
      run: dotnet build MyGithubActionBot/MyGithubActionBot.csproj --configuration Release
      shell: bash

    - name: Run the bot
      run: dotnet run --project MyGithubActionBot/MyGithubActionBot.csproj
      shell: bash
      env:
        GITHUB_TOKEN: ${{ secrets.github-token }}
        GITHUB_WORKSPACE: ${{ inputs.workspace }}
        GITHUB_PULL_REQUEST_NUMBER: ${{ github.event.pull_request.number }}

branding:
  icon: code
  color: blue