name: PR Analysis

on:
  pull_request:
    paths:
      - '**/*.cs'

jobs:
  analyze:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '9.0.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build project
      run: dotnet build --no-restore

    - name: Run PR Analysis
      run: dotnet run --project MyGithubActionBot/MyGithubActionBot.csproj