name: Self-Test

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
      - reopened

jobs:
  example-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Debug Event Payload
        run: cat $GITHUB_EVENT_PATH

      - name: Use MattsPullRequestHelper
        uses: mrlacey/MattsPullRequestHelper@main
        with:
          github-token: ${{ secrets.PR_COMMENT_TOKEN }}
