name: Self-Test

on:
  pull_request:
    paths:
      - '**/*.cs'
    branches:
      - main
    types:
      - opened
      - synchronize
      - reopened

jobs:
  example-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use MattsPullRequestHelper
        uses: mrlacey/MattsPullRequestHelper@main
        with:
          github-token: ${{ secrets.PR_COMMENT_TOKEN }}
